
default:
  log_level: "DEBUG"
  hooks:
    on_load:
      - 'echo "Welcome in your project!"'
    on_shell_run_in:
      - 'echo "Starting shell session..."'
    on_shell_run_out:
      - 'echo "Shell session ended."'
  tmux:
    attach: false
    session_name: "workflow-cli"
    windows:
      - "nvim ."
